name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Test
      run: dotnet test --verbosity normal
    - name: Package library nuget package
      run: dotnet pack src/Html2md.Core/Html2md.Core.csproj --output nuget-packages --configuration Release
    - name: Package dotnet tool nuget package
      run: dotnet pack src/Html2md/Html2md.csproj --output nuget-packages --configuration Release
    - name: Push packages
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

